from aoc_2024 import day_08
from libaoc.vectors import Vect2D

EXAMPLE = """
............
........0...
.....0......
.......0....
....0.......
......A.....
............
............
........A...
.........A..
............
............
"""

def test_parse_input():
    dim, antennas = day_08.parse_input(EXAMPLE)
    assert dim == (12, 12)
    assert len(antennas) == 7
    assert ("0", Vect2D(1, 8)) in antennas
    assert ("A", Vect2D(9, 9)) in antennas


def test_part1():
    dims, antennas = day_08.parse_input(EXAMPLE)
    assert day_08.part_1(dims, antennas) == 14


def test_part2():
    dims, antennas = day_08.parse_input(EXAMPLE)
    assert day_08.part_2(dims, antennas) == 34
